name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get today's date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: set git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: create issue by gh cli
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "${{ steps.date.outputs.date }}"
          git commit --allow-empty -m "経歴書更新(${{ steps.date.outputs.date }})"
          git push --set-upstream origin ${{ steps.date.outputs.date }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
